In [2]:
import numpy as np

In [3]:
# 2D array (matrix)
arr2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

# 3D array (cube of numbers)
arr3d = np.array([
    [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]],

    [[10, 11, 12],
     [13, 14, 15],
     [16, 17, 18]]
])


In [4]:
#Extract the last two columns of the last row in arr2d
arr2d[-1, -2:]


array([11, 12])

In [5]:
#Get every other element from arr2d
arr2d[::2, ::2]

array([[ 1,  3],
       [ 9, 11]])

In [6]:
#Flip arr2d upside down
arr2d[::-1]

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [7]:
#From arr3d, extract the middle row across all layers
arr3d[:, 1, :]


array([[ 4,  5,  6],
       [13, 14, 15]])

In [8]:
#Extract the last column from each layer of arr3d
arr3d[:, :, -1]


array([[ 3,  6,  9],
       [12, 15, 18]])