In [1]:
import numpy as np

In [2]:
data = np.array([[23,19], [100,200], [13, 17]])

print(data)

[[ 23  19]
 [100 200]
 [ 13  17]]


In [6]:
#multiplying the data with 2
multiplied_arr = data*10
print(multiplied_arr)

[[ 230  190]
 [1000 2000]
 [ 130  170]]


In [5]:
#adding the data with itself
added_arr = data + data
print(added_arr)

[[ 46  38]
 [200 400]
 [ 26  34]]


In [14]:
simple_arr = [[23.9, 10.1, 9.3, 10.4], [3.5, 7.1, 90.2, 30.3]]

np_arr = np.array(simple_arr)
print(np_arr)

[[23.9 10.1  9.3 10.4]
 [ 3.5  7.1 90.2 30.3]]


In [15]:
#check the dimensions of numpy array
print(np_arr.ndim)

2


In [11]:
#shape of the numpy array
print(np_arr.shape)

(2, 4)


In [18]:
#check the type of the array
print(np_arr.dtype)
print(data.dtype)

float64
int32


In [ ]:
#one dimensional array with zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [ ]:
#two dimensional array with zeros
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [26]:
#three dimensional array with zeros
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [28]:
np.arange(11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
#type casting
print("type of data before type casting: ", data.dtype)
data = data.astype(np.float64)
print("type of data after type casting: ", data.dtype)

type of data before type casting:  int32
type of data after type casting:  float64


In [33]:
#we can also use another array's dtype to type cast our array's type
integral_arr = np.arange(17)
floating_arr = np.array([[20.8, 10.3, 30.1], [30.3, 10.5, 11.3]])
print("type of integral array before: ", integral_arr.dtype)
integral_arr = integral_arr.astype(floating_arr.dtype)
print("type of integral array after casting: ", integral_arr.dtype)

type of integral array before:  int32
type of integral array after casting:  float64


In [ ]:
#arithmatic operations with numpy arrays

subtracted_arr = integral_arr - integral_arr
print("Subtracted Array: ", subtracted_arr)



[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
#comparison in arrays
arr_1 = np.array([[20, 10], 
                  [30, 40]])
arr_2 = np.array([[11, 30],
                   [20, 19]])
compared_arr = arr_1 > arr_2
print(compared_arr)

[[ True False]
 [ True  True]]


In [60]:
#indexing and slicing
arr = np.arange(13)
print(arr[3:7])

[3 4 5 6]


In [61]:
arr_slice = arr[4:9]
print(arr_slice)

[4 5 6 7 8]


In [63]:
#modifying the elements of arr_slice
arr_slice[2] = 1001
print("Elements of arr_slice: ",arr_slice)
print("Elements of arr: ", arr)

Elements of arr_slice:  [   4    5 1001    7    8]
Elements of arr:  [   0    1    2    3    4    5 1001    7    8    9   10   11   12]
